# SwiftLint Configuration for Printernizer iOS

included:
  - Printernizer

excluded:
  - Printernizer/Sources/Generated

# Rule configurations
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_action
  - private_outlet
  - sorted_imports

# Customizations
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y
    - r
    - g
    - b

type_name:
  min_length:
    warning: 3
    error: 2

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

reporter: "xcode"
